CREATE DATABASE SomeDB;
GO
USE SomeDB;
CREATE TABLE [Buildings]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Adress] NVARCHAR(MAX) NOT NULL,
	[Capacicty] INT NOT NULL,
	[BuildingType] NVARCHAR(100) NOT NULL
)
CREATE TABLE [Workers]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[FirstName] NVARCHAR(100) NOT NULL,
	[LastName] NVARCHAR(150) NOT NULL,
	[PatrName] NVARCHAR(150) NULL,
	[PhoneNumber] NVARCHAR(11) NOT NULL,
	[Speciality] NVARCHAR(250) NOT NULL,
	[BuildingId] INT NOT NULL,
	CONSTRAINT [FK_Workers_Buildings] FOREIGN KEY ([BuildingId]) REFERENCES [Buildings]([Id])
	ON DELETE CASCADE ON UPDATE CASCADE
)